# Практическая работа №1

**Тема**: Загрузка данных.

**Цель работы**: изучение технологии извлечения данных из различных источников: CSV-файлы, Excel-файлы, JSON-файлы, HTML-файлы, SQL-базы данных.

In [ ]:
import pandas as pd

# Часть 1. Чтение CSV-файла
С использованием функции `pd.read_csv()` выполните следующие операции по чтению данных для датасета titanic.csv:

In [2]:
# 1. прочитайте файл и переведите его в датафрейм,
# в качестве индекса используйте столбец 'PassengerId';
df = pd.read_csv('titanic.csv', index_col='PassengerId')
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
# 2. извлеките из файла и сохраните в датафрейм
# первые 10 строк столбцов 'Name', 'Sex' и 'Survived';
df = df[['Name', 'Sex', 'Survived']].head(10)
df

,Name,Sex,Survived
PassengerId,,,
1,"Braund, Mr. Owen Harris",male,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1
3,"Heikkinen, Miss. Laina",female,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1
5,"Allen, Mr. William Henry",male,0
6,"Moran, Mr. James",male,0
7,"McCarthy, Mr. Timothy J",male,0
8,"Palsson, Master. Gosta Leonard",male,0
9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,1
10,"Nasser, Mrs. Nicholas (Adele Achem)",female,1

In [6]:
# 3. прочитайте файл и задайте новый набор
# имен для столбцов в нижнем регистре;
df = pd.read_csv('titanic.csv', index_col='PassengerId')
df.columns = [name.lower() for name in df.columns]
df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
# 4. прочитайте файл, пропустив первые 100 строк,
# а затем считайте следующие 8 строк;
df = pd.read_csv('titanic.csv', index_col='PassengerId')
df.iloc[100:108]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S
102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
104,0,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,NaN,S
105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.9250,NaN,S
106,0,3,"Mionoff, Mr. Stoytcho",male,28.0,0,0,349207,7.8958,NaN,S
107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S
108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S

In [8]:
# 5. прочитайте первые 10 строк из файла, пропустив строки 1, 3, 7.
df = pd.read_csv('titanic.csv')
df.head(10).loc[[0,2,4,5,6,8,9]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# Часть 2. Чтение НТМL-файлов из Интернета
Изучив материал лекции, приведите свой пример на запись НТМL-таблицы в один или несколько объек­тов DataFгame. Продемонстрируйте возможность извлечения части таблицы.

In [9]:
dfs = pd.read_html("persons.html")
print("Кол-во таблиц:", len(dfs))
print(dfs[0])

Кол-во таблиц: 1
   id   Name  Age   Company
0   1    Tom   41    Yandex
1   2    Bob   56        VK
2   3    Sam   31  Sberbank
3   4  Alice   38    Google

# Часть 3. Чтение и запись JSОN-файлов
Изучив материал лекции, приведите свой пример работы с JSОN-файлом.

In [10]:
df = pd.read_json('persons.json')
print(df.head())

    name  age    company
0    Tom   41  Microsoft
1    Bob   56     Google
2    Sam   32     Yandex
3  Alice   38  Microsoft

# Часть 4. Работа с базой данных SQL

In [13]:
# 1. Используя встроенную Python-библиотеку для работы с базами данных - sqlite3
# создайте базу данных для хранения сведений о работе кафе со следующей структурой:
# [структура]
# Самостоятельно подумайте, какие типы данных следует выбрать для полей таблиц.

import sqlite3
conn = sqlite3.connect("cafe.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS Dishes (
    code INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    price REAL NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS Orders (
    number INTEGER PRIMARY KEY,
    date TEXT NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS Ordered (
    code INTEGER PRIMARY KEY,
    order_number INTEGER,
    dish_code INTEGER,
    FOREIGN KEY(order_number) REFERENCES Orders(number),
    FOREIGN KEY(dish_code) REFERENCES Dishes(code)
)
""")

conn.commit()

In [14]:
# 2. Добавьте в таблицу "Блюда" 5 любых блюд, в таблицу "Заказы" - 3 заказа и в каждом заказе по 2-3 блюда (таблица "Заказано").
dishes = [
  (1, "Пицца", 450),
  (2, "Бургер", 320),
  (3, "Паста", 380),
  (4, "Салат", 250),
  (5, "Суп", 200)
]

cursor.executemany("INSERT INTO Dishes VALUES (?, ?, ?)", dishes)

orders = [
  (1, "2025-02-01"),
  (2, "2025-02-02"),
  (3, "2025-02-03")
]

cursor.executemany("INSERT INTO Orders VALUES (?, ?)", orders)

ordered = [
  (1, 1, 1),
  (2, 1, 2),
  (3, 2, 3),
  (4, 2, 4),
  (5, 3, 1),
  (6, 3, 5),
  (7, 3, 4)
]

cursor.executemany("INSERT INTO Ordered VALUES (?, ?, ?)", ordered)
conn.commit()

In [15]:
# 3. С помощью метода read_sql выполните извлечение данных из базы данных и представьте в виде датафрейма:
# 3.1. информацию о заказанных блюдах со следующими столбцами: номер заказа, название блюда, цена.

query = """
SELECT Orders.number AS order_number,
       Dishes.name,
       Dishes.price
FROM Ordered
JOIN Orders ON Ordered.order_number = Orders.number
JOIN Dishes ON Ordered.dish_code = Dishes.code
"""

df1 = pd.read_sql(query, conn)
print(df1)

   order_number    name  price
0             1   Пицца  450.0
1             1  Бургер  320.0
2             2   Паста  380.0
3             2   Салат  250.0
4             3   Пицца  450.0
5             3     Суп  200.0
6             3   Салат  250.0

In [16]:
# 3.2. сумму к оплате для каждого заказа.

query = """
SELECT Orders.number,
       SUM(Dishes.price) AS total
FROM Ordered
JOIN Orders ON Ordered.order_number = Orders.number
JOIN Dishes ON Ordered.dish_code = Dishes.code
GROUP BY Orders.number
"""

df2 = pd.read_sql(query, conn)
print(df2)

   number  total
0       1  770.0
1       2  630.0
2       3  900.0

In [17]:
# 3.3. названия всех блюд, у которых цена меньше 300 руб.

query = """
SELECT name
FROM Dishes
WHERE price < 300
"""

df3 = pd.read_sql(query, conn)
print(df3)

    name
0  Салат
1    Суп

In [18]:
# 3.4. все блюда заказа с номером 2 (или другим номером).

query = """
SELECT Dishes.name
FROM Ordered
JOIN Dishes ON Ordered.dish_code = Dishes.code
WHERE Ordered.order_number = 2
"""

df4 = pd.read_sql(query, conn)
print(df4)

    name
0  Паста
1  Салат

In [19]:
# 3.5. список блюд по убыванию цены.

query = """
SELECT name, price
FROM Dishes
ORDER BY price DESC
"""

df5 = pd.read_sql(query, conn)
print(df5)

     name  price
0   Пицца  450.0
1   Паста  380.0
2  Бургер  320.0
3   Салат  250.0
4     Суп  200.0

In [20]:
# Измените расчёт суммы к оплате, предусмотрев скидку 5% при наличии в заказе 3 и более блюд.

query = """
SELECT Orders.number,
CASE
    WHEN COUNT(Dishes.code) >= 3
    THEN SUM(Dishes.price) * 0.95
    ELSE SUM(Dishes.price)
END AS total_with_discount
FROM Ordered
JOIN Orders ON Ordered.order_number = Orders.number
JOIN Dishes ON Ordered.dish_code = Dishes.code
GROUP BY Orders.number
"""

df_discount = pd.read_sql(query, conn)
print(df_discount)

   number  total_with_discount
0       1                770.0
1       2                630.0
2       3                855.0

In [21]:
# 4. Создайте датафреймы для хранения информации о трёх новых блюдах,
# двух новых заказах, в каждом из которых по 2-3 блюда.
# С помощью метода to_sql выполните запись в базу данных.

new_dishes = pd.DataFrame({
    "code": [6,7,8],
    "name": ["Роллы", "Стейк", "Чай"],
    "price": [500, 700, 120]
})

new_dishes.to_sql("Dishes", conn, if_exists="append", index=False)

new_orders = pd.DataFrame({
    "number": [4,5],
    "date": ["2025-02-04", "2025-02-05"]
})

new_orders.to_sql("Orders", conn, if_exists="append", index=False)

new_ordered = pd.DataFrame({
    "code": [8,9,10,11],
    "order_number": [4,4,5,5],
    "dish_code": [6,8,7,3]
})

new_ordered.to_sql("Ordered", conn, if_exists="append", index=False)

# Закрытие соединения
conn.close()

In [24]:
from os import system

system("jupyter nbconvert --to html practice-1.ipynb")

[NbConvertApp] Converting notebook practice-1.ipynb to html
[NbConvertApp] Writing 338330 bytes to practice-1.html

0